[package]
name = "rotur-icn-renderer"
version = "0.2.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "a wrapper for processing rotur ICNs"
readme = "readme.md"

[lints]
workspace = true

[dependencies]
rayon = { version = "1.11.0", optional = true }
rotur-icn-resolver = { version = "0.2.0", path = "../rotur-icn-resolver" }
rotur-icn-units = { version = "0.1.1", path = "../rotur-icn-units" }
smallvec = { version = "1.15.1", features = ["union"] }

[features]
default = ["rayon"]
rayon = ["dep:rayon"]
